# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/1156/bin/cmake

# The command to remove a file.
RM = /snap/cmake/1156/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/azazzzel/CLionProjects/OOP_CMAKE

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/azazzzel/CLionProjects/OOP_CMAKE

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/snap/cmake/1156/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/cmake/1156/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/azazzzel/CLionProjects/OOP_CMAKE/CMakeFiles /home/azazzzel/CLionProjects/OOP_CMAKE//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/azazzzel/CLionProjects/OOP_CMAKE/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named OOP_CMAKE

# Build rule for target.
OOP_CMAKE: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 OOP_CMAKE
.PHONY : OOP_CMAKE

# fast build rule for target.
OOP_CMAKE/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_CMAKE.dir/build.make CMakeFiles/OOP_CMAKE.dir/build
.PHONY : OOP_CMAKE/fast

Field/Cell.o: Field/Cell.cpp.o
.PHONY : Field/Cell.o

# target to build an object file
Field/Cell.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_CMAKE.dir/build.make CMakeFiles/OOP_CMAKE.dir/Field/Cell.cpp.o
.PHONY : Field/Cell.cpp.o

Field/Cell.i: Field/Cell.cpp.i
.PHONY : Field/Cell.i

# target to preprocess a source file
Field/Cell.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_CMAKE.dir/build.make CMakeFiles/OOP_CMAKE.dir/Field/Cell.cpp.i
.PHONY : Field/Cell.cpp.i

Field/Cell.s: Field/Cell.cpp.s
.PHONY : Field/Cell.s

# target to generate assembly for a file
Field/Cell.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_CMAKE.dir/build.make CMakeFiles/OOP_CMAKE.dir/Field/Cell.cpp.s
.PHONY : Field/Cell.cpp.s

Field/CellType.o: Field/CellType.cpp.o
.PHONY : Field/CellType.o

# target to build an object file
Field/CellType.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_CMAKE.dir/build.make CMakeFiles/OOP_CMAKE.dir/Field/CellType.cpp.o
.PHONY : Field/CellType.cpp.o

Field/CellType.i: Field/CellType.cpp.i
.PHONY : Field/CellType.i

# target to preprocess a source file
Field/CellType.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_CMAKE.dir/build.make CMakeFiles/OOP_CMAKE.dir/Field/CellType.cpp.i
.PHONY : Field/CellType.cpp.i

Field/CellType.s: Field/CellType.cpp.s
.PHONY : Field/CellType.s

# target to generate assembly for a file
Field/CellType.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_CMAKE.dir/build.make CMakeFiles/OOP_CMAKE.dir/Field/CellType.cpp.s
.PHONY : Field/CellType.cpp.s

Field/Field.o: Field/Field.cpp.o
.PHONY : Field/Field.o

# target to build an object file
Field/Field.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_CMAKE.dir/build.make CMakeFiles/OOP_CMAKE.dir/Field/Field.cpp.o
.PHONY : Field/Field.cpp.o

Field/Field.i: Field/Field.cpp.i
.PHONY : Field/Field.i

# target to preprocess a source file
Field/Field.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_CMAKE.dir/build.make CMakeFiles/OOP_CMAKE.dir/Field/Field.cpp.i
.PHONY : Field/Field.cpp.i

Field/Field.s: Field/Field.cpp.s
.PHONY : Field/Field.s

# target to generate assembly for a file
Field/Field.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_CMAKE.dir/build.make CMakeFiles/OOP_CMAKE.dir/Field/Field.cpp.s
.PHONY : Field/Field.cpp.s

GameControl/ComandController.o: GameControl/ComandController.cpp.o
.PHONY : GameControl/ComandController.o

# target to build an object file
GameControl/ComandController.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_CMAKE.dir/build.make CMakeFiles/OOP_CMAKE.dir/GameControl/ComandController.cpp.o
.PHONY : GameControl/ComandController.cpp.o

GameControl/ComandController.i: GameControl/ComandController.cpp.i
.PHONY : GameControl/ComandController.i

# target to preprocess a source file
GameControl/ComandController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_CMAKE.dir/build.make CMakeFiles/OOP_CMAKE.dir/GameControl/ComandController.cpp.i
.PHONY : GameControl/ComandController.cpp.i

GameControl/ComandController.s: GameControl/ComandController.cpp.s
.PHONY : GameControl/ComandController.s

# target to generate assembly for a file
GameControl/ComandController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_CMAKE.dir/build.make CMakeFiles/OOP_CMAKE.dir/GameControl/ComandController.cpp.s
.PHONY : GameControl/ComandController.cpp.s

GameControl/Game.o: GameControl/Game.cpp.o
.PHONY : GameControl/Game.o

# target to build an object file
GameControl/Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_CMAKE.dir/build.make CMakeFiles/OOP_CMAKE.dir/GameControl/Game.cpp.o
.PHONY : GameControl/Game.cpp.o

GameControl/Game.i: GameControl/Game.cpp.i
.PHONY : GameControl/Game.i

# target to preprocess a source file
GameControl/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_CMAKE.dir/build.make CMakeFiles/OOP_CMAKE.dir/GameControl/Game.cpp.i
.PHONY : GameControl/Game.cpp.i

GameControl/Game.s: GameControl/Game.cpp.s
.PHONY : GameControl/Game.s

# target to generate assembly for a file
GameControl/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_CMAKE.dir/build.make CMakeFiles/OOP_CMAKE.dir/GameControl/Game.cpp.s
.PHONY : GameControl/Game.cpp.s

Input-Output/ComandReader.o: Input-Output/ComandReader.cpp.o
.PHONY : Input-Output/ComandReader.o

# target to build an object file
Input-Output/ComandReader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_CMAKE.dir/build.make CMakeFiles/OOP_CMAKE.dir/Input-Output/ComandReader.cpp.o
.PHONY : Input-Output/ComandReader.cpp.o

Input-Output/ComandReader.i: Input-Output/ComandReader.cpp.i
.PHONY : Input-Output/ComandReader.i

# target to preprocess a source file
Input-Output/ComandReader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_CMAKE.dir/build.make CMakeFiles/OOP_CMAKE.dir/Input-Output/ComandReader.cpp.i
.PHONY : Input-Output/ComandReader.cpp.i

Input-Output/ComandReader.s: Input-Output/ComandReader.cpp.s
.PHONY : Input-Output/ComandReader.s

# target to generate assembly for a file
Input-Output/ComandReader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_CMAKE.dir/build.make CMakeFiles/OOP_CMAKE.dir/Input-Output/ComandReader.cpp.s
.PHONY : Input-Output/ComandReader.cpp.s

Input-Output/FieldView.o: Input-Output/FieldView.cpp.o
.PHONY : Input-Output/FieldView.o

# target to build an object file
Input-Output/FieldView.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_CMAKE.dir/build.make CMakeFiles/OOP_CMAKE.dir/Input-Output/FieldView.cpp.o
.PHONY : Input-Output/FieldView.cpp.o

Input-Output/FieldView.i: Input-Output/FieldView.cpp.i
.PHONY : Input-Output/FieldView.i

# target to preprocess a source file
Input-Output/FieldView.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_CMAKE.dir/build.make CMakeFiles/OOP_CMAKE.dir/Input-Output/FieldView.cpp.i
.PHONY : Input-Output/FieldView.cpp.i

Input-Output/FieldView.s: Input-Output/FieldView.cpp.s
.PHONY : Input-Output/FieldView.s

# target to generate assembly for a file
Input-Output/FieldView.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_CMAKE.dir/build.make CMakeFiles/OOP_CMAKE.dir/Input-Output/FieldView.cpp.s
.PHONY : Input-Output/FieldView.cpp.s

Input-Output/TextOutput.o: Input-Output/TextOutput.cpp.o
.PHONY : Input-Output/TextOutput.o

# target to build an object file
Input-Output/TextOutput.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_CMAKE.dir/build.make CMakeFiles/OOP_CMAKE.dir/Input-Output/TextOutput.cpp.o
.PHONY : Input-Output/TextOutput.cpp.o

Input-Output/TextOutput.i: Input-Output/TextOutput.cpp.i
.PHONY : Input-Output/TextOutput.i

# target to preprocess a source file
Input-Output/TextOutput.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_CMAKE.dir/build.make CMakeFiles/OOP_CMAKE.dir/Input-Output/TextOutput.cpp.i
.PHONY : Input-Output/TextOutput.cpp.i

Input-Output/TextOutput.s: Input-Output/TextOutput.cpp.s
.PHONY : Input-Output/TextOutput.s

# target to generate assembly for a file
Input-Output/TextOutput.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_CMAKE.dir/build.make CMakeFiles/OOP_CMAKE.dir/Input-Output/TextOutput.cpp.s
.PHONY : Input-Output/TextOutput.cpp.s

Mediator/MediatorController.o: Mediator/MediatorController.cpp.o
.PHONY : Mediator/MediatorController.o

# target to build an object file
Mediator/MediatorController.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_CMAKE.dir/build.make CMakeFiles/OOP_CMAKE.dir/Mediator/MediatorController.cpp.o
.PHONY : Mediator/MediatorController.cpp.o

Mediator/MediatorController.i: Mediator/MediatorController.cpp.i
.PHONY : Mediator/MediatorController.i

# target to preprocess a source file
Mediator/MediatorController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_CMAKE.dir/build.make CMakeFiles/OOP_CMAKE.dir/Mediator/MediatorController.cpp.i
.PHONY : Mediator/MediatorController.cpp.i

Mediator/MediatorController.s: Mediator/MediatorController.cpp.s
.PHONY : Mediator/MediatorController.s

# target to generate assembly for a file
Mediator/MediatorController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_CMAKE.dir/build.make CMakeFiles/OOP_CMAKE.dir/Mediator/MediatorController.cpp.s
.PHONY : Mediator/MediatorController.cpp.s

Mediator/MediatorObj.o: Mediator/MediatorObj.cpp.o
.PHONY : Mediator/MediatorObj.o

# target to build an object file
Mediator/MediatorObj.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_CMAKE.dir/build.make CMakeFiles/OOP_CMAKE.dir/Mediator/MediatorObj.cpp.o
.PHONY : Mediator/MediatorObj.cpp.o

Mediator/MediatorObj.i: Mediator/MediatorObj.cpp.i
.PHONY : Mediator/MediatorObj.i

# target to preprocess a source file
Mediator/MediatorObj.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_CMAKE.dir/build.make CMakeFiles/OOP_CMAKE.dir/Mediator/MediatorObj.cpp.i
.PHONY : Mediator/MediatorObj.cpp.i

Mediator/MediatorObj.s: Mediator/MediatorObj.cpp.s
.PHONY : Mediator/MediatorObj.s

# target to generate assembly for a file
Mediator/MediatorObj.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_CMAKE.dir/build.make CMakeFiles/OOP_CMAKE.dir/Mediator/MediatorObj.cpp.s
.PHONY : Mediator/MediatorObj.cpp.s

Player/Player.o: Player/Player.cpp.o
.PHONY : Player/Player.o

# target to build an object file
Player/Player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_CMAKE.dir/build.make CMakeFiles/OOP_CMAKE.dir/Player/Player.cpp.o
.PHONY : Player/Player.cpp.o

Player/Player.i: Player/Player.cpp.i
.PHONY : Player/Player.i

# target to preprocess a source file
Player/Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_CMAKE.dir/build.make CMakeFiles/OOP_CMAKE.dir/Player/Player.cpp.i
.PHONY : Player/Player.cpp.i

Player/Player.s: Player/Player.cpp.s
.PHONY : Player/Player.s

# target to generate assembly for a file
Player/Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_CMAKE.dir/build.make CMakeFiles/OOP_CMAKE.dir/Player/Player.cpp.s
.PHONY : Player/Player.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_CMAKE.dir/build.make CMakeFiles/OOP_CMAKE.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_CMAKE.dir/build.make CMakeFiles/OOP_CMAKE.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOP_CMAKE.dir/build.make CMakeFiles/OOP_CMAKE.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... OOP_CMAKE"
	@echo "... Field/Cell.o"
	@echo "... Field/Cell.i"
	@echo "... Field/Cell.s"
	@echo "... Field/CellType.o"
	@echo "... Field/CellType.i"
	@echo "... Field/CellType.s"
	@echo "... Field/Field.o"
	@echo "... Field/Field.i"
	@echo "... Field/Field.s"
	@echo "... GameControl/ComandController.o"
	@echo "... GameControl/ComandController.i"
	@echo "... GameControl/ComandController.s"
	@echo "... GameControl/Game.o"
	@echo "... GameControl/Game.i"
	@echo "... GameControl/Game.s"
	@echo "... Input-Output/ComandReader.o"
	@echo "... Input-Output/ComandReader.i"
	@echo "... Input-Output/ComandReader.s"
	@echo "... Input-Output/FieldView.o"
	@echo "... Input-Output/FieldView.i"
	@echo "... Input-Output/FieldView.s"
	@echo "... Input-Output/TextOutput.o"
	@echo "... Input-Output/TextOutput.i"
	@echo "... Input-Output/TextOutput.s"
	@echo "... Mediator/MediatorController.o"
	@echo "... Mediator/MediatorController.i"
	@echo "... Mediator/MediatorController.s"
	@echo "... Mediator/MediatorObj.o"
	@echo "... Mediator/MediatorObj.i"
	@echo "... Mediator/MediatorObj.s"
	@echo "... Player/Player.o"
	@echo "... Player/Player.i"
	@echo "... Player/Player.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

